name: Push
on: [push]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10']
        poetry-version: ['1.3.2']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: lock
        run: poetry lock --no-update
      - name: install package
        run: poetry install
      - name: activate env
        run: source `poetry env info --path`/bin/activate
      - name: install bowtie2
        run: echo -e "Y\n" | sudo apt-get install bowtie2
      - name: run unit tests
        run: poetry run pytest -m "not integtest" 
      - name: run integration test
        run: poetry run pytest -m "integtest"
  docs:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9']
        poetry-version: ['1.3.2']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: lock
        run: poetry lock --no-update
      - name: install
        run: poetry install -E docs    
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc
      - name: Build docs
        run: | 
          mkdir gh-pages
          touch gh-pages/.nojekyll
          cd docs/
          poetry run sphinx-build -b html . _build
          cp -r _build/* ../gh-pages/
      - name: Deploy documentation
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: gh-pages

  
