name: Push
on: [push]

jobs:
  set_up:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        poetry-version: ['1.3.2']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: print python version 
        run: python -V  # Print out python version for debugging
      - name: install poetry
        run: pip install poetry
      - name: install package
        run: poetry install
      - name: activate env
        run: source `poetry env info --path`/bin/activate
      - name: update apt-get
        run: apt-get update
      - name: install bowtie2
        run: echo -e "Y\n" | apt-get install bowtie2




  unit_tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        poetry-version: ['1.3.2']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: [set_up]
    steps:
      - name: cd
        run: cd tests
      - name: run unit tests
        run: pytest -m "not integtest" 

  integration_tests:
    needs: [before_script]
    steps:
      - echo "Running integration test..."
      - cd tests
      - pytest -m "integtest"
  
