name: Push
on: [push]

image: python:3.10


# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/
jobs:
  before_script:
    steps:
      - python -V  # Print out python version for debugging
      - pip install poetry
      - poetry install
      - source `poetry env info --path`/bin/activate
      
      - apt-get update
      - echo -e "Y\n" | apt-get install bowtie2
      #- pip install pandas
      #- pip install numpy
      #- pip install numba
      #- pip install psutil
      #- pip install biopython
      #- pip install regex
      #- pip install pytest
      #- pip install scipy
      #- pip install scikit-learn
      #- pip install matplotlib
      #- pip install click



  unit_tests:
    needs: [before_script]
    steps:
      - echo "Running unit tests..."
      - cd tests
      - pytest -m "not integtest" 

  integration_tests:
    needs: [before_script]
    steps:
      - echo "Running integration test..."
      - cd tests
      - pytest -m "integtest"
  
